### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Telesphoreo** [Adaptified/Freedom#1]
While I merely skimmed through the code can you make it so admins can bypass bans? because I'm banned lol

also is Utils still in development

**Comment by mgejay** [comment]
Yes, it is. Just putting to the side for a little while.

**Comment by Telesphoreo** [comment]
ok

**Comment by mgejay** [comment]
This is also an enhancement, no need to close! @PacksGamingHD

**Comment by Telesphoreo** [comment]
Oh the admin bypass

Yeah it'd be nice if there was a rogue
